### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by jyy1752645604** [marujore/LaSRC-LEDAPS-Fmask#5]
![image](https://user-images.githubusercontent.com/48400277/119259051-f6b3d500-bbfe-11eb-869c-44d2d760f38f.png)

**Comment by marujore** [comment]
@jyy1752645604 plz try again to check if it wasn't any unstability during the weekend.
If it continues not working try replacing (on the Dockerfile)
`RUN curl https://git.earthdata.nasa.gov/rest/git-lfs/storage/DAS/hdfeos/cb0f900d2732ab01e51284d6c9e90d0e852d61bba9bce3b43af0430ab5414903?response-content-disposition=attachment%3B%20filename%3D%22HDF-EOS2.20v1.00.tar.Z%22%3B%20filename*%3Dutf-8%27%27HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z`
by
`RUN curl https://distfiles.macports.org/hdfeos/HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z`

**Comment by jyy1752645604** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much! Now I have built the larsc image through the Dockerfile successfully as seen the 1st picture. However, two problems appeared when I processed the Landsat 8 (seen in the 2nd picture) and Sentinel-2 (seen in the 3rd picture) data. And I cant solve those problems by myself. If you can help me, I'll be very grateful. Looking forward to your early reply. Thanks again.Best WishesYoung JinNanjing university, Jiangsu Province, China.
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Young
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/24/2021 19:51，Rennan ***@***.***> wrote： 



@jyy1752645604 plz try again to check if it wasn't any unstability during the weekend.
If it continues not working try replacing (on the Dockerfile)
RUN curl https://git.earthdata.nasa.gov/rest/git-lfs/storage/DAS/hdfeos/cb0f900d2732ab01e51284d6c9e90d0e852d61bba9bce3b43af0430ab5414903?response-content-disposition=attachment%3B%20filename%3D%22HDF-EOS2.20v1.00.tar.Z%22%3B%20filename*%3Dutf-8%27%27HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z
by
RUN curl https://distfiles.macports.org/hdfeos/HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jyy1752645604** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Yeah! Sorry to disturb you. I have solved these problems. If I have other problems, I will contact you again. Thanks again.Best WishesYoung Jin
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Young
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/6/2021 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much! Now I have built the larsc image through the Dockerfile successfully as seen the 1st picture. However, two problems appeared when I processed the Landsat 8 (seen in the 2nd picture) and Sentinel-2 (seen in the 3rd picture) data. And I cant solve those problems by myself. If you can help me, I'll be very grateful. Looking forward to your early reply. Thanks again.Best WishesYoung JinNanjing university, Jiangsu Province, China.
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Young
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/24/2021 19:51，Rennan ***@***.***> wrote： 



@jyy1752645604 plz try again to check if it wasn't any unstability during the weekend.
If it continues not working try replacing (on the Dockerfile)
RUN curl https://git.earthdata.nasa.gov/rest/git-lfs/storage/DAS/hdfeos/cb0f900d2732ab01e51284d6c9e90d0e852d61bba9bce3b43af0430ab5414903?response-content-disposition=attachment%3B%20filename%3D%22HDF-EOS2.20v1.00.tar.Z%22%3B%20filename*%3Dutf-8%27%27HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z
by
RUN curl https://distfiles.macports.org/hdfeos/HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jyy1752645604** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        A same problem (about the directory: /usr/GERS/Fmask_4_3/application/run_Fmask_4_3.sh) appeared when I processed the Landsat 8 and Sentinel-2 data. And I don't know how to fix the directory by myself. If you can help me, I'll be very grateful. Looking forward to your early reply. Thanks again.Best WishesYoung JinNanjing university, Jiangsu Province, China.
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Young
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/6/2021 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Yeah! Sorry to disturb you. I have solved these problems. If I have other problems, I will contact you again. Thanks again.Best WishesYoung Jin
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Young
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/6/2021 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much! Now I have built the larsc image through the Dockerfile successfully as seen the 1st picture. However, two problems appeared when I processed the Landsat 8 (seen in the 2nd picture) and Sentinel-2 (seen in the 3rd picture) data. And I cant solve those problems by myself. If you can help me, I'll be very grateful. Looking forward to your early reply. Thanks again.Best WishesYoung JinNanjing university, Jiangsu Province, China.
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Young
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/24/2021 19:51，Rennan ***@***.***> wrote： 



@jyy1752645604 plz try again to check if it wasn't any unstability during the weekend.
If it continues not working try replacing (on the Dockerfile)
RUN curl https://git.earthdata.nasa.gov/rest/git-lfs/storage/DAS/hdfeos/cb0f900d2732ab01e51284d6c9e90d0e852d61bba9bce3b43af0430ab5414903?response-content-disposition=attachment%3B%20filename%3D%22HDF-EOS2.20v1.00.tar.Z%22%3B%20filename*%3Dutf-8%27%27HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z
by
RUN curl https://distfiles.macports.org/hdfeos/HDF-EOS2.20v1.00.tar.Z -o /tmp/hdfeos.tar.Z

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
